# Generated by Django 5.1.6 on 2025-03-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.URLField(blank=True, default='https://i.imgur.com/VzvjjDg.jpeg', null=True),
        ),
    ]
