# Generated by Django 5.1.6 on 2025-03-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'School'), (2, 'Home'), (3, 'Random'), (4, 'Friends')], primary_key=True, serialize=False),
        ),
    ]
