# Generated by Django 5.1.6 on 2025-03-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
